services:
  metabase:
    build:
      context: .
      dockerfile: Dockerfile.metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=h2
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - ./metabase-data:/metabase-data
      - ./db:/app/db

  data-processing:
    build:
      context: .
      dockerfile: Dockerfile.data-processing
    volumes:
      - ./db:/app/db
