name: kitsuna
description: The one-person data and BI platform
services:
  - name: metabase
    dockerfile_path: Dockerfile.metabase
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
        domains:
          - metabase.kitsunadata.com
  - name: data-processing
    dockerfile_path: Dockerfile.data-processing
    instance_size_slug: basic-xxs
    instance_count: 1
mounts:
  - source: duckdb-data
    destination: /duckdb-data
